FROM shadowsocks/shadowsocks-libev:v3.3.5

# default
#ENV SERVER_ADDR 0.0.0.0
#ENV SERVER_PORT 8388
#ENV PASSWORD=
#ENV METHOD      aes-256-gcm
#ENV TIMEOUT     300
#ENV DNS_ADDRS    8.8.8.8,8.8.4.4
#ENV TZ UTC
#ENV ARGS=

#CMD /entrypoint.sh